name: week_3
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.3
  retrofit_generator: ^10.0.6
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.9.0
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1

flutter_native_splash:
  color: "#9775FA"
  image: assets/master/splash_screen.png
  android_12:
    image: assets/master/splash_screen.png
    color: "#9775FA"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/master/
